### ISSUE TITLE
Add Zones to the map

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#10]
Mission Bay/Rock: King St to 16th St
Pier 70: 16th to Islais Creek (if that's too general maybe use Cesar Chavez St)
India Basin: Islais Creek (or Cargo Way) to Innes Ave
Candlestick/Shipyard: Innes Ave to Jamestown Ave

Western boundaries are 101/80 for all.

**Comment by almccon** [comment]
Rough outlines (I can clean them up if we like them) 
https://stamen.cartodb.com/u/stamen-org/viz/da5304bc-efd0-11e5-b112-0e5db1731f59/public_map

![screen shot 2016-03-21 at 6 54 49 pm](https://cloud.githubusercontent.com/assets/1212178/13939924/6c650430-ef96-11e5-9bdc-e92d3f85243d.png)

**Comment by almccon** [comment]
Currently @clhenrick has a zones overlay using https://github.com/stamen/bluegreenway/blob/master/geodata/bluegreenway_zones.geojson

and I have them in subtle colors in the basemap:
https://stamen.cartodb.com/u/stamen-org/viz/4d180fa8-0e3d-11e6-aa9a-0ea31932ec1d/public_map

<img width="155" alt="screen shot 2016-05-17 at 17 may 1 42 51" src="https://cloud.githubusercontent.com/assets/1212178/15338555/4c01881e-1c35-11e6-8fd0-d9c9164716dd.png">
