### ISSUE TITLE
homepage takes way too long to load

### ISSUE THREAD

**Issue by ericsoco** [stamen/bluegreenway#104]
This is the first thing people see when they come to the site. We're currently hitting their slow-ass CMS three times before anything but the header shows up. We need to come up with a better solution.

A loading indicator / progress bar / spinner is the absolute minimum. We should have real content appear asap, even if it comes in in stages.

@clhenrick, do you know if Packery can relayout after adding more content to its data list? Can we progressively show more content as the CMS requests come in, instead of showing all or nothing?

/cc @alecburch to give some design thought to this.

**Comment by clhenrick** [comment]
@ericsoco I noticed that the delay was about ~2-3 seconds for me, was it worse when you noticed it? 

We could try not loading `projects` on the homepage and see if that cuts down. Not sure about Packery, might be worth testing, though I think going with a simple solution such as a spinner is ideal.

**Comment by ericsoco** [comment]
I'm pretty positive it's not a client side issue, the CMS calls are just
slow.

Ah, didn't realize we were loading projects on the homepage -- why is that?
We should definitely not do that if they're not being used there.

It's 2-3 sec on our fast internet. My shitty AT&T service at home yielded
up to 10s.

**Comment by ericsoco** [comment]
Downgrading to p2. Good enough for board presentation, not enough for launch IMO.

**Comment by ericsoco** [comment]
This is actually due to #176; the prod CMS feeds are relatively fast, each coming in at < 1s on a throttled DSL connection.
