### ISSUE TITLE
zone images are too large

### ISSUE THREAD

**Issue by ericsoco** [stamen/bluegreenway#105]
We should downsample them and serve the smaller size, instead of squeezing 1600x900px into a lil' ~490x280px box.

I'm not sure if there's anywhere currently that we'd need the fullsize images, but we should hold onto them in case, and save the downsampled images as separate files and edit the zones geojson to match.

@alecburch what size should we aim for per your design (keep in mind mobile, tablet, desktop), and can you please downsample the `zone-*.jpg` images [here](https://github.com/stamen/bluegreenway/tree/master/static/img)?

**Comment by alecburch** [comment]
resized and dropped them here: https://drive.google.com/drive/u/0/folders/0B_SHIf8wsjgNRTBCRC1XSFROVlU

**Comment by almccon** [comment]
Updated in cdba1a4d25e81e39d07704e5878e5d48c997486e
