### ISSUE TITLE
Add colors to the story categories

### ISSUE THREAD

**Issue by alecburch** [stamen/bluegreenway#107]
# b895c9
# 49a3be
# 8bc954
# 043d58
# 2e7042
# ffb933

**Comment by alecburch** [comment]
also, the color of the overlay should be the same as the category cover. currently everything is blue.

**Comment by ericsoco** [comment]
the category labels at upper-left specifically, e.g. 
![screen shot 2016-06-21 at 2 16 27 pm](https://cloud.githubusercontent.com/assets/1127259/16246609/c9efbf16-37ba-11e6-94d1-7ec8c32c838f.png)
