### ISSUE TITLE
Recreation and shore locations (via Ports)

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#11]
Recreation and shore locations
http://www.sfport.com/sites/default/files/FileCenter/Documents/4399-BG_Base_Map_BoatAccess.pdf

**Comment by almccon** [comment]
This is one of the datasets for #7

**Comment by almccon** [comment]
The only data in that PDF that fits the description of "recreation and shore locations" is the planned and existing boat access.

I manually extracted those here: https://bluegreenway.cartodb.com/tables/boat_access/map and uploaded the geojson to github for good measure: b94f4e86d4ee22168979bddf6d89d263f932540a

![screen shot 2016-05-24 at 24 may 4 00 44](https://cloud.githubusercontent.com/assets/1212178/15522798/b3f0e692-21c9-11e6-96a0-28983dcc0378.png)

Are there other features we need for "recreation and shore locations"?

**Comment by almccon** [comment]
Assuming this is all we need
