### ISSUE TITLE
Left align logo in nav bar with content

### ISSUE THREAD

**Issue by alecburch** [stamen/bluegreenway#111]
![screen shot 2016-06-16 at 11 26 51 am](https://cloud.githubusercontent.com/assets/5263476/16128519/dd527a34-33b5-11e6-9ebb-fc0e7a6e9577.png)

**Comment by ericsoco** [comment]
@alecburch align logo to content? or content to logo?
currently, the logo is `1rem` from the left edge. your mocks show the logo and content aligned as such. so i _think_ we should be bumping the content out, not the logo in. ?

**Comment by alecburch** [comment]
that works.
