### ISSUE TITLE
Text on Zone pages is too large

### ISSUE THREAD

**Issue by alecburch** [stamen/bluegreenway#112]
In general, text on the zones pages is quite large. For reference:

https://marvelapp.com/141icj3#10762760

**Comment by ericsoco** [comment]
@alecburch it's hard to get accurate sizing from the marvel app because it rescales with the browser window. do you have point sizes? (i think there was a doc?) everything's in `rem`s but that's relative to `24px` IIRC so we can do the math to get from `px` to `rem`.

**Comment by alecburch** [comment]
i made this doc a while back https://docs.google.com/a/stamen.com/spreadsheets/d/1ldFSq590ApsbPpAWCal__8vZWg9iDZcldhkcQU0sHno/edit?usp=drive_web

**Comment by alecburch** [comment]
need to add zone page deets though.

**Comment by ebrelsford** [comment]
@alecburch It would be helpful to have specific values if you can provide them. Is there any chance this is a duplicate of #102?

**Comment by alecburch** [comment]
this was cleaned up along the way somewhere.
