### ISSUE TITLE
Fix people story text justification on home page

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#118]

**Comment by ericsoco** [comment]
![screen shot 2016-06-21 at 2 20 59 pm](https://cloud.githubusercontent.com/assets/1127259/16246747/6d71f758-37bb-11e6-8cfe-232fc7bceb94.png)

!=

![screen shot 2016-06-21 at 2 21 06 pm](https://cloud.githubusercontent.com/assets/1127259/16246748/6d876eb2-37bb-11e6-8ce9-e313446896f9.png)

**Comment by ericsoco** [comment]
Should look like:
![screen shot 2016-06-21 at 3 12 31 pm](https://cloud.githubusercontent.com/assets/1127259/16248201/a89d735a-37c2-11e6-8047-0a4ab521db69.png)

I styled it already by looking at Mr. Rump, and that's still working correctly, so I'm guessing there are styles coming from the CMS that need to be `!important`-overridden.

**Comment by ericsoco** [comment]
Done.
