### ISSUE TITLE
Descriptive text should have consistent line height

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#119]
On home page for stories

**Comment by ericsoco** [comment]
![screen shot 2016-06-21 at 2 22 39 pm](https://cloud.githubusercontent.com/assets/1127259/16246797/a81bbfc4-37bb-11e6-945b-47afa6f00ebd.png)

vs. 

![screen shot 2016-06-21 at 2 22 45 pm](https://cloud.githubusercontent.com/assets/1127259/16246798/a81cfa10-37bb-11e6-9e48-b0cad6a44d42.png)

**Comment by ericsoco** [comment]
Done.
