### ISSUE TITLE
media queries break on navigation

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#120]
Repro: load site to home page, click on Story nav, result is fucked up layout

**Comment by clhenrick** [comment]
Data is being mutated on the homepage when it shouldn't be:
![screen shot 2016-06-21 at 4 50 48 pm](https://cloud.githubusercontent.com/assets/161748/16250257/d33f6ab0-37d0-11e6-8f85-112199a43fbe.png)

vs. loading directly on the Stories route:
![screen shot 2016-06-21 at 4 51 57 pm](https://cloud.githubusercontent.com/assets/161748/16250259/d4f81a1e-37d0-11e6-8c04-84316e338dae.png)

Notice `homepage: true` is present in a Story object when loading the app on the index route.

**Comment by ericsoco** [comment]
Turns out it had nothing to do with media queries, it was the state mutation @clhenrick described above.
Fixed by https://github.com/stamen/bluegreenway/commit/c088347f9478fec19aaeb5db0ba3589ccad26060.
