### ISSUE TITLE
Zone page - turn off extra stuff

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#127]
Turn off extra junk on the map in the zone view pages

**Comment by ericsoco** [comment]
"junk" == everything except base layer.
See https://github.com/stamen/bluegreenway/blob/master/src/components/LeafletMap.js#L156-L159 and https://github.com/stamen/bluegreenway/blob/master/src/views/Projects.jsx#L132-L135

**Comment by ericsoco** [comment]
@clhenrick did this.
