### ISSUE TITLE
Trim India Basin Zone Text

### ISSUE THREAD

**Issue by alecburch** [stamen/bluegreenway#130]
Ask client to limit zone text to 50 word limit.

**Comment by ericsoco** [comment]
Whoops. Realized this is coming from the geojson, not the CMS. @almccon will update.

**Comment by ericsoco** [comment]
Closed via https://github.com/stamen/bluegreenway/commit/e25936d868fe872b39eab29a8686e0c5155fbd53 and https://github.com/stamen/bluegreenway/commit/6a5cc1e2df0711fb8d6004a553155fdc76a9ffc6
