### ISSUE TITLE
create icons for things on map

### ISSUE THREAD

**Issue by alecburch** [stamen/bluegreenway#134]
benches, boat launches, etc

**Comment by ericsoco** [comment]
subset of #48

**Comment by alecburch** [comment]
Icons for benches, picnic tables, and boat launches. 

[map icons.zip](https://github.com/stamen/bluegreenway/files/328686/map.icons.zip)

**Comment by alecburch** [comment]
who's implementing? @almccon or @ericsoco ?

**Comment by almccon** [comment]
✋

**Comment by ericsoco** [comment]
@almccon happy to have you do it, but FYI i have an SVG icon build pipeline setup so please check in with me first.

**Comment by almccon** [comment]
But they're burned into the cartodb basemap overlay layer, no? Or has that changed?

**Comment by ericsoco** [comment]
Oh right. Thanks @almccon ;)

**Comment by almccon** [comment]
I'm sourcing them from the github repo right now, but I should switch it to use use a bluegreenway.org url once we've deployed that.

I welcome suggestions from @alecburch about color choices:

![screen shot 2016-06-24 at 24 jun 5 20 16](https://cloud.githubusercontent.com/assets/1212178/16353480/f34f3d60-3a2f-11e6-9441-0756f55ad65f.png)

Current code: 

```
#combined_poi_tables {   
   marker-placement: point;   
   marker-width: 10;
   marker-allow-overlap: true;
}

#combined_poi_tables[type="Bench"] {
  marker-file: url(https://raw.githubusercontent.com/stamen/bluegreenway/2be95328f1c356ddc1d86dc99427cd21b2440593/static/icons/icon_bench.svg);
  marker-fill: #725555;
  marker-transform: scale(2.0,2.0);
  [zoom<=13] { marker-transform: scale(1.2,1.2); }
}
#combined_poi_tables[type="Picnic Table"] {
  marker-file: url(https://raw.githubusercontent.com/stamen/bluegreenway/56922e84cb38eaf19a23c33ef1a5ece467c84d80/static/icons/icon_picnic-table.svg);
  marker-fill: #12700c;
  marker-transform: scale(2.0,2.0);
  [zoom<=13] { marker-transform: scale(1.2,1.2); }
}
#combined_poi_tables[type="Boat Existing"] {
  marker-fill: #1f78b4;
}
#combined_poi_tables[type="Boat Planned"] {
  marker-fill: #666;
}
#combined_poi_tables[type="Boat Existing"],
#combined_poi_tables[type="Boat Planned"] {
  marker-file: url(https://raw.githubusercontent.com/stamen/bluegreenway/56922e84cb38eaf19a23c33ef1a5ece467c84d80/static/icons/icon_boat-launch.svg);
  marker-transform: scale(3.5,3.5);
  [zoom<=13] { marker-transform: scale(2,2); }
}
```

**Comment by alecburch** [comment]
Sorry I'm late. 

Benches: #8bc954
Tables: #279ab7
Boats, existing: #043d58
Boats, planned: #ffff98

**Comment by almccon** [comment]
Updated.

![screen shot 2016-07-05 at 5 jul 1 03 20](https://cloud.githubusercontent.com/assets/1212178/16598050/e6967622-42b0-11e6-9fa4-78af46b9773b.png)

Do we have/need a legend for these?

**Comment by almccon** [comment]
Yes, tracking the legend needs in #91, so closing this.

**Comment by alecburch** [comment]
Errrr, that planned boat launch is...impossible to read. 

Can we change it to #efc100.

**Comment by almccon** [comment]
Done.
![screen shot 2016-07-06 at 6 jul 12 24 34](https://cloud.githubusercontent.com/assets/1212178/16631573/a28021b2-4374-11e6-9d7b-12a77b120141.png)
