### ISSUE TITLE
header image isn't full width

### ISSUE THREAD

**Issue by alecburch** [stamen/bluegreenway#138]
on all pages other than the home page the header image is about 5 pixels short of being fullwidth. you can see the overlay _is_ going the full width.

![screen shot 2016-06-21 at 2 02 58 pm](https://cloud.githubusercontent.com/assets/5263476/16246233/3276c5d6-37b9-11e6-87b9-852c4c0eb421.png)

**Comment by ericsoco** [comment]
I'm not seeing this, guess it was fixed.
