### ISSUE TITLE
Stack multiple tile layers in Leaflet instead of using a single viz.json

### ISSUE THREAD

**Issue by almccon** [stamen/bluegreenway#150]
For our free plan on CartoDB, we can only have four layers. As implemented now, the top three are the POIs, the bike network, and the green connections network. Then I use `UNION ALL` in SQL to combine everything else into the fourth layer, which is my true basemap (includes water, roads, parcels, projects, labels, etc). This fourth layer is everything which is visible permanently, and the top three are toggled on and off as layers within the CartoDB viz.json (see #66 and 3c082dab525b7b675445b0199ab94158aeae3f56).

However, in order to make the labels (#148) and the bluegreenway line (#149) look good, I need more control over the ordering. I need the toggleable layers to stay underneath the labels and the bluegreenway.

Do we have time to rearchitect the map so that we load more than one viz.json from CartoDB, and (potentially) toggle layers on and off by setting the visibility of the leaflet layer, rather than toggling layers _within_ a single viz.json? Toggling in Leaflet might eliminate the flicker that happens when the CartoDB toggle triggers a full reload of the tiles.

@clhenrick I'll probably need your help with this because I'm not sure how/where to do this in a react app. Thoughts?

**Comment by almccon** [comment]
Currently this is the single viz.json we're using: https://bluegreenway.cartodb.com/viz/7d66aa96-2eb0-11e6-a298-0ecfd53eb7d3/map

I'm going to split that up into multiple layers, each with their own viz.json. Will post links here shortly.

**Comment by almccon** [comment]
Labels and BGW line: https://bluegreenway.cartodb.com/viz/5b9d66e2-2c57-423c-a594-f06704c5d9b4/map
Basemap: https://bluegreenway.cartodb.com/viz/81e43dc0-f481-46e8-ad8f-9794ca285e55/map
All three toggle layers together: https://bluegreenway.cartodb.com/viz/525c8bf9-d550-4ac5-8643-248dedfdea9b/map

Or, separate toggle layers:

POIs: https://bluegreenway.cartodb.com/viz/536ca7e4-54e1-4608-a6d6-1fd81cd51703/map
Bicycle: https://bluegreenway.cartodb.com/viz/7136fdf4-5972-488c-97fd-12062e6950fb/map
Green Connections: https://bluegreenway.cartodb.com/viz/97832533-8ab7-4b22-8164-1f1fc6a37885/map

**Comment by clhenrick** [comment]
thanks @almccon
