### ISSUE TITLE
Create lower-res images

### ISSUE THREAD

**Issue by ericsoco** [stamen/bluegreenway#169]
Many of the images in [here](https://github.com/stamen/bluegreenway/tree/master/static/img) are too big for web, they load super slow. @alecburch please Photoshop Save For Web them or whatever you like to use for that. And downsample them to a px size appropriate for their display on the site kthx.

Probably easiest to pile them into a Dropbox folder, then I'll bring them into the project.

**Comment by ericsoco** [comment]
Related: #168

**Comment by alecburch** [comment]
Everything was sized appropriately accept the defaults for events. I resized them and placed them here. I also created retina friendly versions. 

https://drive.google.com/drive/u/0/folders/0B_SHIf8wsjgNQm90LWF1aDJFX1E

**Comment by alecburch** [comment]
New new event images here. Going through others now. 
https://drive.google.com/drive/u/0/folders/0B_SHIf8wsjgNQm90LWF1aDJFX1E

**Comment by alecburch** [comment]
Header images about a third of the previous size.

https://drive.google.com/drive/u/0/folders/0B_SHIf8wsjgNZEk0dmd5NzJRMkU

**Comment by ericsoco** [comment]
Closed via https://github.com/stamen/bluegreenway/commit/d0957b8ac96129f7c142598eb32da9c4459343e0
