### ISSUE TITLE
Add filter button on home page map. 

### ISSUE THREAD

**Issue by alecburch** [stamen/bluegreenway#172]
For some reason there isn't one.

**Comment by ericsoco** [comment]
Huh? Filter what?

**Comment by ericsoco** [comment]
oh, like this thing
![screen shot 2016-07-07 at 1 30 35 pm](https://cloud.githubusercontent.com/assets/1127259/16668734/0aee9918-4447-11e6-9c5b-4533009b7c57.png)

got it.
