### ISSUE TITLE
Zones/Projects layout on mobile

### ISSUE THREAD

**Issue by alecburch** [stamen/bluegreenway#174]
Current format has the line width and image really really small. 

Let's make the paragraphs full width and the images full width below the text. Like:

![screen shot 2016-07-07 at 11 12 36 am](https://cloud.githubusercontent.com/assets/5263476/16664232/0ae83a5e-4434-11e6-88ca-9338fa0c7ede.png)

**Comment by ericsoco** [comment]
This is already done.
