### ISSUE TITLE
Dancing project descriptions 

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#175]
Win 10, Chrome Version 51.0.2704.103 m

**Comment by ericsoco** [comment]
I tested on Win 10 / Chrome 51 on browserstack and cannot repro.
I did notice a little jitter on Win 8 / Chrome 51, but the elements still opened.

Tried searching for any Windows bugs with `react-collapse` or `react-motion` and couldn't find anything.
I'm inclined to close this as I can't repro...sorry @emilyhobson .
