### ISSUE TITLE
Put a background on this story, it looks weird the way it is

### ISSUE THREAD

**Issue by ericrodenbeck** [stamen/bluegreenway#183]
http://stamen.github.io/bluegreenway/#/stories/page/Paddling_on_the_Bay?id=6357

![Uploading Screen Shot 2016-07-08 at 4.20.00 PM.png…]()

**Comment by emilyhobson** [comment]
Screen shot?

**Comment by ericsoco** [comment]
Don't understand. Looks like the screenshot didn't upload, @ericrodenbeck . When I click that URL, everything looks fine to me.

**Comment by emilyhobson** [comment]
@ericrodenbeck ?

**Comment by ericrodenbeck** [comment]
Agreed, closing
