### ISSUE TITLE
Treat benches like labels; if they overlap, show just one

### ISSUE THREAD

**Issue by ericrodenbeck** [stamen/bluegreenway#187]
http://stamen.github.io/bluegreenway/#/about/map/

It doesn't matter which one gets preference over the other, just that they don't overlap

<img width="168" alt="screen shot 2016-07-08 at 4 28 09 pm" src="https://cloud.githubusercontent.com/assets/450233/16704182/13177578-4529-11e6-9cce-074b1a42e3ca.png">

**Comment by almccon** [comment]
<img width="71" alt="screen shot 2016-07-08 at 8 jul 4 44 37" src="https://cloud.githubusercontent.com/assets/1212178/16704387/52705e9a-452b-11e6-9b45-f9de11f36d58.png">
Fixed
