### ISSUE TITLE
Old events showing up on home page and Events map view

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#189]
Pins are showing up for past events 

http://stamen.github.io/bluegreenway/#/events/map/

![image](https://cloud.githubusercontent.com/assets/824082/16704219/68cdd980-4529-11e6-8d24-e48274877e16.png)

**Comment by ericsoco** [comment]
Yeah, we're not filtering events on the map page. We should be.

**Comment by ericsoco** [comment]
And now there's only one event showing on the map. 🙍  Ah well.
