### ISSUE TITLE
Scrolling popup box with stories is too tall for viewport

### ISSUE THREAD

**Issue by almccon** [stamen/bluegreenway#197]
Perhaps related to the fact that the left menu bars also don't fit my viewport.

Here is my typical layout for my retina macbook screen:

<img width="1280" alt="screen shot 2016-07-25 at 25 jul 5 03 41" src="https://cloud.githubusercontent.com/assets/1212178/17121657/16196e8e-528a-11e6-986f-8f39982f0d33.png">

It happens on the new build, and the old one:

![bgw_bug2_old_site](https://cloud.githubusercontent.com/assets/1212178/17121676/29b35a2c-528a-11e6-8d0a-094272d99eed.gif)
![bgw_bug2](https://cloud.githubusercontent.com/assets/1212178/17121675/29b33d62-528a-11e6-8cd9-6ae42daadfca.gif)

**Comment by ericsoco** [comment]
Can't repro, probably long-since fixed.
