### ISSUE TITLE
Image and link to PDF

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#201]
Include a thumbnail and link to the brochure PDF (does not need to be lightbox) on the about page.

**Comment by alecburch** [comment]
If we move the twitter feed to the home page this could work. clicking on the thumbnail opens the image in a lightbox. 
![screen shot 2016-10-13 at 10 26 14 am](https://cloud.githubusercontent.com/assets/5263476/19359565/9d0f7e68-912f-11e6-9d8e-8b05740ae7bc.png)

**Comment by ericsoco** [comment]
2 hours max

**Comment by emilyhobson** [comment]
Provide a button or callout or dingbat "Download the brochure" to make it clear you can act against the image. Clicking opens the PDF. @alecburch

**Comment by ericsoco** [comment]
![screen shot 2016-10-24 at 11 03 03 am](https://cloud.githubusercontent.com/assets/1127259/19657551/8a8ef4dc-99d9-11e6-91e8-0d6c50763f5e.png)
