### ISSUE TITLE
Twitter location

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#202]
Will this look ok?
Mockup first

**Comment by alecburch** [comment]
my first thought was to put it under the grid but that felt like an afterthought. other options are to put it _in_ the grid or in the footer. if we put it in the footer we have to think about how images would be treated, how many tweets to include, etc. for those reasons, i think putting it in the grid may be easier although we'd have to rethink the grid logic then. with that said, i would prefer to just leave it on the about page. i feel like having it front and center of the home page is distracting. 

![screen shot 2016-10-13 at 9 52 10 am](https://cloud.githubusercontent.com/assets/5263476/19358434/beba49ee-912a-11e6-9703-b1b0c0d4707e.png)

**Comment by ericsoco** [comment]
Not easy to put it in the grid. Hard to estimate, but substantial.

**Comment by emilyhobson** [comment]
What about in the footer if the footer content gets tightened and it flows on the right? In mobile it would tuck under the reset of the footer links.

![image](https://cloud.githubusercontent.com/assets/824082/19489157/dcdbcbda-951e-11e6-9abb-f3fd22baa0f3.png)

**Comment by emilyhobson** [comment]
Moving the Twitter feed was a by-product of including the brochure, so let's revisit the best place to put the feed (my vote is footer)

**Comment by emilyhobson** [comment]
![image](https://cloud.githubusercontent.com/assets/824082/19540529/f7586012-9614-11e6-9e99-3eeac24c28e7.png)

**Comment by ericsoco** [comment]
@alecburch and I just talked IRL. We're gonna try some version of that ^^ sketch.

**Comment by ericsoco** [comment]
Also closed by https://github.com/stamen/bluegreenway/commit/f85c46a58dc2426a9b481ce7e309c88527325fdb
