### ISSUE TITLE
Treat past events in homepage

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#203]
Removing the past events may interfere with the grid. Can they be replaced with color blocks?

Mockup first

**Comment by alecburch** [comment]
easy fix would be to use the default images we already use for the event tiles sans copy. so just the image.

**Comment by ericsoco** [comment]
yep, that was my suggestion as well @alecburch

**Comment by ericsoco** [comment]
![screen shot 2016-10-18 at 11 49 47 am](https://cloud.githubusercontent.com/assets/1127259/19491764/0842021c-9529-11e6-9cf6-c2331cc67449.png)
