### ISSUE TITLE
possible mobile device de-bugging

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#206]

**Comment by emilyhobson** [comment]
![image](https://cloud.githubusercontent.com/assets/824082/19540507/cfdf52e8-9614-11e6-8a26-70791310fc74.png)
Story map view pin interaction
Iphone
Homepage
Map
Tap on any marker
Pop up appears off right edge of screen
Emily also can repro on her android

![image](https://cloud.githubusercontent.com/assets/824082/19540513/d4b8b16a-9614-11e6-9870-907d28307bc1.png)
stories map view layers interaction

**Comment by ericsoco** [comment]
I can't repro the latter -- it works fine on the emulator and my phone... :/
Can anyone else ( @almccon @alecburch ) see the map filters all jacked up as in @emilyhobson's screenshot above? If so, platform?

**Comment by almccon** [comment]
I am seeing some kinda weird behavior on iOS 10, iPhone 5:

![slack for ios upload png](https://cloud.githubusercontent.com/assets/1212178/19670404/db6d1dec-9a1b-11e6-9d82-5dfb0890a1ac.jpeg)

![slack for ios upload-1 png](https://cloud.githubusercontent.com/assets/1212178/19670408/e1efff04-9a1b-11e6-9186-0369d3cadccb.jpeg)

**Comment by ericsoco** [comment]
Closed via 829fb8237b8769ad05b25164913edc54c1a3494c and d024339b3e76df8dfb30f2d2c35bbb74178d6081
