### ISSUE TITLE
Fix & in legend

### ISSUE THREAD

**Issue by alecburch** [stamen/bluegreenway#209]
& is showing as `&amp;` on legend. 

<img width="288" alt="screen shot 2016-10-25 at 9 43 26 am" src="https://cloud.githubusercontent.com/assets/5263476/19695369/cdccf992-9a97-11e6-9a08-6fc12ecd36c9.png">

**Comment by ericsoco** [comment]
Closed via https://github.com/stamen/bluegreenway/commit/7d2f3b0591d8681667fe55059e2eef3d52478c3d
