### ISSUE TITLE
Include newsletter sign up in prominent location

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#210]
Will go to confirmation page so should new tab
We'll need the form code, obv
Location tbd

**Comment by emilyhobson** [comment]
"Unfortunately we don't have a code snippet for the Blue Greenway Email signup as we had to create it as a survey on our website. Is it possible to just link out "Sign up for Blue Greenway updates" to the following page?

http://sfpa.convio.net/site/Survey?ACTION_REQUIRED=URI_ACTION_USER_REQUESTS&SURVEY_ID=1540

**Comment by ericsoco** [comment]
Closed via f87d46f20cb2edeaa413bbda89dd783f021a66dc
![screen shot 2016-11-07 at 1 55 40 pm](https://cloud.githubusercontent.com/assets/1127259/20077613/edee590a-a4f1-11e6-8942-a384cb324161.png)
