### ISSUE TITLE
Preview PDF on screen

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#211]
Instead of downloading the PDF on click, preview in window. Permit download method from preview (backed into method)
Option: ( re PDF embeds -> https://pdfobject.com/

**Comment by ericsoco** [comment]
![screen shot 2016-11-07 at 1 54 58 pm](https://cloud.githubusercontent.com/assets/1127259/20077574/d29354e4-a4f1-11e6-91fe-0aca4657bfcb.png)
