### ISSUE TITLE
Project shape: Separate Warriors/Chase Center from Bayfront Park

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#213]
These are combined in the map (shape) for Chase Center, but should be separated. If we need a new project ID, Evan or May can create. In face, Bayfront Park shape doesn't appear from Project detail map link.
![image](https://cloud.githubusercontent.com/assets/824082/20026192/7864d3a6-a2b4-11e6-8ac1-10053f2ce18b.png)

Bayfront Park is 3 parcels 1) P22 south street to 16th east side of Terry Francois Boulevard(TFB) and 2&3) 16th street to Mariposa  west side of TFB all of which equal about 8 acres.

Chase: https://en.wikipedia.org/wiki/File:Chase_Center,_San_Francisco_%E2%80%93_Map,_April_2016,_zoom_17.png ??

**Comment by almccon** [comment]
Okay, I split the shape into two objects. Chase Center retains the `bgw_id` of 6388 which should correspond to the CMS. For Bayfront Park I created a made-up `bgw_id` of 6388000, which needs to be replaced when we know the real ID in the CMS. Or if the real ID already exists, I forgot how to check what it is. 

I also haven't deployed the change, I'll let @ericsoco do that when we think it's ready.

**Comment by ericsoco** [comment]
You did deploy the change, @almccon ;) The data file you edited is pulled by the prod application.
We're all good. Deploying a related fix now.
