### ISSUE TITLE
More prominent social media icons

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#214]
Larger  on the footer

**Comment by ericsoco** [comment]
Closed via f87d46f20cb2edeaa413bbda89dd783f021a66dc
![screen shot 2016-11-07 at 1 55 40 pm](https://cloud.githubusercontent.com/assets/1127259/20077633/06eed402-a4f2-11e6-95d3-d3d3430ea4ab.png)

(Note: still need larger (2x) icons from @alecburch, but I'm just closing this anyway to minimize clutter.)
