### ISSUE TITLE
Need 2x social icons

### ISSUE THREAD

**Issue by ericsoco** [stamen/bluegreenway#215]
currently have 25x25 and 50x50, need double-res.

![buttons_desktop-facebook](https://cloud.githubusercontent.com/assets/1127259/20357299/4474cdae-abdc-11e6-9e6b-eb819f5be20a.png)
![buttons_desktop-facebook 2x](https://cloud.githubusercontent.com/assets/1127259/20357303/447afcba-abdc-11e6-9771-0f41b3a7e11f.png)
![buttons_desktop-instagram](https://cloud.githubusercontent.com/assets/1127259/20357300/44779124-abdc-11e6-99d1-27e400a6e2eb.png)
![buttons_desktop-instagram 2x](https://cloud.githubusercontent.com/assets/1127259/20357301/447967b0-abdc-11e6-9321-46a897d5fab3.png)
![buttons_desktop-twitter](https://cloud.githubusercontent.com/assets/1127259/20357302/447afada-abdc-11e6-95cf-ca1f3526891e.png)
![buttons_desktop-twitter 2x](https://cloud.githubusercontent.com/assets/1127259/20357304/447d358e-abdc-11e6-9848-cba7128d3670.png)

**Comment by alecburch** [comment]
New guys

[social media.zip](https://github.com/stamen/bluegreenway/files/598100/social.media.zip)
