### ISSUE TITLE
Map blur

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#25]

**Comment by ebrelsford** [comment]
Potentially like [Bklyn Bridge Park](http://www.brooklynbridgepark.org/)'s background image.

**Comment by ericsoco** [comment]
@ebrelsford theirs works well, feel free to rip off their solution if it's better than what I was suggesting. (Haven't looked into the details.)

**Comment by ebrelsford** [comment]
We're doing this with CSS currently but if we wanted to support IE up to 11 we could do something like [this](http://bl.ocks.org/ebrelsford/e6da185a965dd1f3a121503780761557).

**Comment by ericsoco** [comment]
Just to clarify @ebrelsford, does the CSS-only solution work on IE11?
We want to support IE11+, but since this is just cosmetic and functionality is not affected, it's fine if we don't let IE11 in on this party.

**Comment by ebrelsford** [comment]
The CSS-only solution will not work on IE11. It depends on `filter`, which [has support](http://caniuse.com/#feat=css-filters) on everything but IE11 and below.
