### ISSUE TITLE
Mobile views 

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#27]
Assign to @ebrelsford after pointing to design files, @alecburch

**Comment by alecburch** [comment]
mobile: https://marvelapp.com/11jc0d5

tablet: https://marvelapp.com/1g7i6e4

**Comment by ebrelsford** [comment]
- [x] Mobile menu (#44)
- [x] Grid width
- [x] Grid cell sizes
- [x] Page margin
- [x] Footer
- [x] Story detail view (images overflow)
- [x] Map filters
- [x] Font sizes

**Comment by ebrelsford** [comment]
@alecburch I think the functionality for the mobile views is in a pretty good place. If you can provide feedback on font sizes and spacing when you have a moment that would be helpful.

**Comment by ericsoco** [comment]
New subissue list:
- [x] ~~When I load the site on my iPhone, nothing appears...??~~
  Looks like it's just me, so not gonna worry about this one... --@ericsoco
- [X] ~~Can't pan the map on mobile~~ emulator-only, not a real problem
- [X] Center MAP/PAGE buttons (https://github.com/stamen/bluegreenway/commit/e7c8366891ea080f5dd9bfd906b28b479ce6b520)
- [X] Don't format People stories as tall on homepage (https://github.com/stamen/bluegreenway/commit/773e53d152af821ddf80be8b353d8d58ec14ead8)
- [X] Move images below text in individual projects on Zone page (https://github.com/stamen/bluegreenway/commit/5038589727ae2fa00900752771b4ea9da698b11c)
- [X] Narrow the margins in individual projects on Zone page (https://github.com/stamen/bluegreenway/commit/5038589727ae2fa00900752771b4ea9da698b11c)
- [X] Increase About page font-size (https://github.com/stamen/bluegreenway/commit/8086a70becf2657828af159a457d359f7b7763cf)
- [X] Vertically center contents of hamburger menu (https://github.com/stamen/bluegreenway/commit/ff254ecf75b21958dae09e565d710e81355616a7)
- [x] Events/stories map popups should be fullscreen, dismissable modals

**Comment by ericsoco** [comment]
I think this is pretty good now, so imma close it. @alecburch feel free to take one last pass on mobile if you like.
