### ISSUE TITLE
Tablet views 

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#28]

**Comment by alecburch** [comment]
mobile: https://marvelapp.com/11jc0d5

tablet: https://marvelapp.com/1g7i6e4

**Comment by ebrelsford** [comment]
To do:
- [ ] Footer way too large
- [ ] You should not be able to scroll the page on any of the map views
- [ ] Projects: Leaflet maps seem to be absorbing all touch events (making scrolling difficult)
- [ ] In portrait orientation the menu overlaps with the logo (need to use mobile-style menu here)
- [ ] In portrait orientation, text overflows header images

**Comment by ericsoco** [comment]
Copying Brelz' items here so he doesn't get notification spammed as I work on them.
- [X] Footer way too large (https://github.com/stamen/bluegreenway/commit/0dee057a407de796e0ac678825f25b3eb1551684)
- [X] You should not be able to scroll the page on any of the map views (https://github.com/stamen/bluegreenway/commit/9a7f9a518d6f2d150fef46d038dae5a7bae27783)
- [X] Projects: Leaflet maps seem to be absorbing all touch events (making scrolling difficult) (can't repro)
- [X] In portrait orientation the menu overlaps with the logo (need to use mobile-style menu here) (https://github.com/stamen/bluegreenway/commit/381bc307f17275fbdc25fe82526cc9efe377ebca)
- [X] In portrait orientation, text overflows header images (https://github.com/stamen/bluegreenway/commit/c2e3672b881991b0f2a73e99b5a01814c7f30b0c)
