### ISSUE TITLE
Make header like Medium's

### ISSUE THREAD

**Issue by ebrelsford** [stamen/bluegreenway#31]
Scroll down, it hides. Scroll back up, it reappears.

**Comment by clhenrick** [comment]
@alecburch can you give me a better description than the one above? Or is this something we can put off to phase 2/3?

**Comment by alecburch** [comment]
Here is a demo: http://jsfiddle.net/mariusc23/s6mLJ/31/

**Comment by clhenrick** [comment]
Thanks for the fiddle!

**Comment by clhenrick** [comment]
Seems busted now, reopening issue. Looks like it's broken on larger Desktop screen sizes.

**Comment by ericsoco** [comment]
Repro: on my Macbook (1680x1050), scrolling down and then back up on the home page, it always stays hidden.

Also, the scroll handler isn't being throttled. lodash's `throttle` is a good way to handle this.
