### ISSUE TITLE
Choose and implement radio button list React component for Map layers

### ISSUE THREAD

**Issue by ericsoco** [stamen/bluegreenway#35]
or just write from scratch, if there's not a radio button component that has a very simple API and small footprint.

**Comment by clhenrick** [comment]
@ericsoco what part of the app will this be for? Toggling map layers?

**Comment by ericsoco** [comment]
Correct. I think @ebrelsford already did this?

**Comment by ebrelsford** [comment]
Pretty much, but they're just vanilla checkboxes right now, might want to be componented a bit.
