### ISSUE TITLE
Add projects as GeoJSON overlay layer to map

### ISSUE THREAD

**Issue by ericsoco** [stamen/bluegreenway#40]
meta-issue that can be broken into parts and closed once work starts.
can maybe follow example [here](https://github.com/americanpanorama/panorama-canals/blob/master/src/App.jsx#L777-L810)

**Comment by almccon** [comment]
@ebrelsford Try this sample `bgw_projects.geojson` if you want to get started: https://github.com/stamen/bluegreenway/blob/f3f8adb16f7e8008c921d32e3a4e7f97b0157869/geodata/bgw_projects.geojson

It's by no means a final list, and the shapes aren't finalized either. Oh, and the ID numbers are all made up, but I did use a lot of the `Associated Location` IDs currently coming from the test `events.json` feed, so if you link those to the `bgw_id` in the GeoJSON, you could get events associating themselves with shapes. Certainly the wrong shapes, but shapes nonetheless.

**Comment by almccon** [comment]
Also, if you want to move that file to some folder other than `geodata/` that's fine with me too.

**Comment by almccon** [comment]
I assume that it will be relatively easy to add these shapes as overlays... nothing too fancy there, right @ericsoco?

**Comment by almccon** [comment]
I will keep refining the shapes as we go forward, and I can get involve with styling the GeoJSON once they're on the map, but I think wiring them up to the map will be on @ericsoco.

**Comment by clhenrick** [comment]
@almccon assuming that these shapes be static and that the client won't be updating them?

**Comment by almccon** [comment]
Yeah, they'll be static, as far as I'm aware. I expect they _will_ need to adjust them, but we aren't providing any interface for them to do this on their own. The'll have to have us update the shapes.

**Comment by almccon** [comment]
`http://dev.sfparksalliance.org/feeds/locations.json` ought to be the source of truth for the project IDs, so I will update the GeoJSON file to match those IDs where possible.

**Comment by almccon** [comment]
Currently only two entities in `locations.json` have `"Is BGW": "1"` (all the rest are `null`). So I'll have to look up the IDs for the others manually by searching through the feed and trying to see which names matchup.

**Comment by almccon** [comment]
Okay, whenever I could find real IDs in `locations.json` I updated them in `bgw_projects.geojson`. But when I _couldn't_ find IDs, I set the id = `999999`.

**Comment by clhenrick** [comment]
@almccon thanks for the heads up. Are we also mapping stories and events?

**Comment by almccon** [comment]
My understanding is that we will only map them using the project location that they fall within. They won't have geometries of their own. But I could be wrong on that.

**Comment by emilyhobson** [comment]
Point please

**Comment by almccon** [comment]
It looks like @clhenrick has this working, but unstyled: 
![screen shot 2016-05-24 at 4 13 31 pm](https://cloud.githubusercontent.com/assets/1212178/15523131/0488d378-21cd-11e6-869a-c142a0cc61d1.png)

**Comment by clhenrick** [comment]
@alecburch @almccon any ideas for a color? Not my forte.

**Comment by alecburch** [comment]
Maybe try coloring based on their zones for now. Same color and opacity so that the two build on each other and you can see the areas where there are no parks. You'll need to add an outline then too, so when two parks are next to each other you can see where one ends and the other begins.

**Comment by clhenrick** [comment]
Closing this and creating a new issue for Projects Polygon Styling.
