### ISSUE TITLE
Add .htaccess to redirect to project root

### ISSUE THREAD

**Issue by ebrelsford** [stamen/bluegreenway#42]
Make it possible to go to URLs other than root on studio

**Comment by clhenrick** [comment]
@mojodna @ericsoco looking toward you for guidance how to set this.

**Comment by sethfitz** [comment]
From https://github.com/ericsoco/transmoteV4/blob/8c74edb95611bfb28ba1a842df53fbe8e5528f04/server-config/htaccess-projects#L19-L25:

Adding the following to `.htaccess` in relevant `show/` directories should work:

```
RewriteEngine On

# html5 pushstate (history) support
# from: http://www.josscrowcroft.com/2012/code/htaccess-for-html5-history-pushstate-url-routing/
RewriteCond %{REQUEST_FILENAME} !-f
# diasallow access to any subfolders
#RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !index
RewriteRule ^.*$ ../index.html [QSA,L,NE]
```

**Comment by clhenrick** [comment]
cool thanks!

**Comment by clhenrick** [comment]
@seth I added this in the last build and didn't seem to help. Would be good to debug it sometime.

**Comment by ericsoco** [comment]
Don't spend much time on it. It's not a requirement by any means; our final
build target may or may not be running Apache.
