### ISSUE TITLE
Mobile menu

### ISSUE THREAD

**Issue by ebrelsford** [stamen/bluegreenway#44]

**Comment by ericsoco** [comment]
@emilyhobson what is the difference between this and #27? Is it something that needs to happen this phase?

**Comment by ebrelsford** [comment]
@alecburch Do we have inverted social media icons for the bottom of the mobile menu? I only see icons with a blue background but your designs have a white background.

**Comment by alecburch** [comment]
[mobile social media buttons.zip](https://github.com/stamen/bluegreenway/files/330554/mobile.social.media.buttons.zip)
