### ISSUE TITLE
Integrate map into site as background, map 

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#47]
@clhenrick Check with @almccon for details

**Comment by almccon** [comment]
We're going to pull the basemap from CartoDB for the time being:
https://stamen.cartodb.com/u/stamen-org/viz/4d180fa8-0e3d-11e6-aa9a-0ea31932ec1d/map

I'll iterate on this map, I'll keep the link the same.

**Comment by clhenrick** [comment]
@almccon will any parts of the basemap be interactive, or will it just serve as a static background tile layer?
