### ISSUE TITLE
add marker legend to map view

### ISSUE THREAD

**Issue by clhenrick** [stamen/bluegreenway#48]
per Alec's mock: 

![screen shot 2016-05-06 at 1 25 41 pm](https://cloud.githubusercontent.com/assets/161748/15080889/2d3b9cf8-138e-11e6-8291-18cb9f2729a0.png)

**Comment by ericsoco** [comment]
#159 suggests there should be one of these for Event types as well, and that the legends should double as category toggles.

**Comment by emilyhobson** [comment]
Let's stick with the legend usage for now and not pursue toggles.
