### ISSUE TITLE
Event data feed

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#5]
Feed from CMS
Surface only Events only tied to BGW locations

**Comment by clhenrick** [comment]
events are being pulled in to `/events/page` but the event map locations and detail pages aren't yet implemented.

**Comment by clhenrick** [comment]
@alecburch will individual events have their own page, similar to individual story pages?

**Comment by clhenrick** [comment]
event filters need to be implemented.

**Comment by clhenrick** [comment]
closing this and opening a new issue for event filters
