### ISSUE TITLE
add transparent overlays to story/event tiles.

### ISSUE THREAD

**Issue by alecburch** [stamen/bluegreenway#54]
Let's just do one color for stories and one for events right now. 

8bc954 at 35% opacity for events.

49a3be a5 35% opacity for stories. 

The point of this is to tone back the images and also make the text more readable. Adding a drop shadow, like on the header image, may be helpful also.

**Comment by clhenrick** [comment]
👍

**Comment by clhenrick** [comment]
I'd imagine the same will go for the site Header @alecburch?

**Comment by alecburch** [comment]
Right, yes. 043d58 at 20% for all the header images.

**Comment by clhenrick** [comment]
@alecburch how about for "About" and "Projects"?

**Comment by alecburch** [comment]
Are you referring to the header images? They should all have the same transparency. 043d58 at 20%.

**Comment by clhenrick** [comment]
@emilyhobson we need images in the BGW test events so I can make sure this is working once it is enabled.

**Comment by alecburch** [comment]
Can I get you placeholder ones? I'd like there to be 6 or so default images that are used if there isn't an image for an event.

**Comment by clhenrick** [comment]
@alecburch that's a great idea, thank you!

**Comment by alecburch** [comment]
dropped 6 default images here:

https://drive.google.com/drive/u/0/folders/0B_SHIf8wsjgNQm90LWF1aDJFX1E

**Comment by clhenrick** [comment]
Great, thanks
