### ISSUE TITLE
deal with abrupt ending of map south of Candlestick

### ISSUE THREAD

**Issue by almccon** [stamen/bluegreenway#57]
It looks awkward because all of our city data ends at the edge of the city (obviously) but this is compounded by the fact that the coastline just happens to straighten out right at that spot. 

![screen shot 2016-05-17 at 17 may 3 37 02](https://cloud.githubusercontent.com/assets/1212178/15341738/63630c98-1c45-11e6-82d0-08ffec50b192.png)

Options: 
- source similar data (bike network, parcels, etc) from Daly City and Brisbane and South SF etc.
- Add freeways or something everywhere
- Add a hillshade or contours everywhere?

**Comment by almccon** [comment]
Maybe the fixed zoom/extent from #53 would make this irrelevant? Not sure.

**Comment by clhenrick** [comment]
If we made the zone locator maps static images and fixed sizes then we could use the static maps API to generate them and not have to deal with using Leaflet, CartoDB.JS, GET requests, etc: https://docs.cartodb.com/cartodb-platform/maps-api/static-maps-api/

**Comment by almccon** [comment]
@clhenrick would that make things easier for you? Or is it just one more API you'd have keep track of?

**Comment by clhenrick** [comment]
@almccon I was thinking / hoping you could render the maps using this API or via the static image export in the CartoDB dashboard. 

Don't worry about it now, but in the future when we need to show static maps this would be a huge time saver as I spent about 8 - 12 hours creating / debugging them using Cartodb.js and getting them to work with React & React Router.

**Comment by almccon** [comment]
Ahh, good to know, sorry about that! I figured naively that adding a few more leaflet maps using an existing style would be fairly simple, rather than using a different workflow to produce these as static maps. Definitely something to note in the future.

**Comment by almccon** [comment]
Since the locator maps are looking good now, we don't need to deal with this problem. Re-open if that changes in the future.
