### ISSUE TITLE
lack of test data blocking build

### ISSUE THREAD

**Issue by clhenrick** [stamen/bluegreenway#58]
for Projects & Events. 

To implement the build for the existing mocks I need actual BGW specific data, which we don't have.

cc @emilyhobson

**Comment by clhenrick** [comment]
This is more for Projects then Events, though I'm still unsure of how we will be able to map events if they don't have specific addresses associated with them. I'm aware @almccon stated we will do a join with some geo data, but am uncertain of what the said geodata is. Relates to #52

**Comment by emilyhobson** [comment]
Is this showing up in the locations feed, @clhenrick http://dev.sfparksalliance.org/our-parks/parks/herons-head-park-test

**Comment by clhenrick** [comment]
Yes it is. Though I'm only seeing 4 items in the projects / locations feed @emilyhobson. Comparing this with @alecburch's mock:

![screen shot 2016-05-24 at 10 10 44 am](https://cloud.githubusercontent.com/assets/161748/15507002/d04c0ec0-2197-11e6-8dd6-32319bbc51af.png)

Keep in mind there are 4 project zones, the above is the page for one zone. Where do all the items under "Open Spaces" come from?

**Comment by almccon** [comment]
Regarding the question about the Open Spaces, there's now #61 to track that.

**Comment by emilyhobson** [comment]
Four are in the dev CMS so that's correct.
