### ISSUE TITLE
Store all geodata in BGW CartoDB

### ISSUE THREAD

**Issue by clhenrick** [stamen/bluegreenway#59]
Need this to happen for the map view to be implemented. Will also pull the basemap from a new `vis.json` created in the BGW CartoDB account. 

cc @almccon @emilyhobson

**Comment by almccon** [comment]
Here is the new `viz.json` for the basemap https://bluegreenway.cartodb.com/api/v2/viz/670bca0d-c029-4e70-bdb9-1bb1c3ce1e77/viz.json

**Comment by almccon** [comment]
The zones are in the table `bluegreenway_zones`, but you can keep referencing the version on github if you prefer `https://github.com/stamen/bluegreenway/blob/master/geodata/bluegreenway_zones.geojson`

**Comment by almccon** [comment]
Similarly, the projects are in the table `bgw_projects`, but the github version should be considered the source of truth: `https://github.com/stamen/bluegreenway/blob/master/geodata/bgw_projects.geojson`

**Comment by clhenrick** [comment]
@almccon one downside of grouping multiple layers in CartoDB (as you're currently doing with `bicycle_network`) is that I can't toggle individual layers on or off (`bicycle_network` and `green_connections_network_final`). Not sure if those two layers are meant to be actually grouped as one layer or if you're just getting around the number of layers in a viz limitation of the CartoDB free account. We may need to keep this in mind for #66.

**Comment by almccon** [comment]
Yeah, I think I grouped them together because we were thinking in #66 that we'd group the filters together. I agree that the hacky UNIONing of tables is only worth it when we need to get around the limitations of the free account, and we shouldn't do it if we ever think we're going to need to split layers apart in the front end.

**Comment by almccon** [comment]
Everything is in CartoDB, and the filters and grouping discussion goes in #66, so I'm closing this.
