### ISSUE TITLE
Emphasis on Open Spaces map features 

### ISSUE THREAD

**Issue by almccon** [stamen/bluegreenway#61]
In @alecburch's mockup: https://marvelapp.com/141icj3#10988099 there is a list of open spaces in each zone, distinct from the project in each zone.
![screen shot 2016-05-24 at 24 may 8 41 08](https://cloud.githubusercontent.com/assets/1212178/15510188/4a3e0736-218b-11e6-9da3-e1e77cf663d5.png)

How are these supposed to work? Do we have a page for each of these? Do we highlight them on the map when you click them?

We do have a file of open spaces from the planning department [planning_openspaces.geojson](https://github.com/stamen/bluegreenway/blob/master/geodata/planning_openspaces.geojson), but I was only using that to extract the openspaces which are also BGW projects.

![screen shot 2016-05-24 at 24 may 8 43 04](https://cloud.githubusercontent.com/assets/1212178/15510261/8f4e1d3e-218b-11e6-8074-dddbd696848b.png)

**Comment by emilyhobson** [comment]
They will need their own location (and ID) via the CMS. Can they then be tied to the shapes? We'll only show the ones in the BGW zones.

**Comment by almccon** [comment]
I can intersect this file with the zones, so we'll only show ones in the zones. But to assign IDs to all of them, I'll need the CMS to have names that exactly match the names in this file.

**Comment by emilyhobson** [comment]
Treat with emphasis, but otherwise these are locations, category = parks and will require the same secondary ID mapping as the other locations.

**Comment by almccon** [comment]
I'm going to add a `category` field to the `bgw_projects.geojson` file, with two possible values: `park` and `project`.

**Comment by almccon** [comment]
Update: I'm using the values `open space` or `project`.

See:
![screen shot 2016-06-07 at 7 jun 1 06 59](https://cloud.githubusercontent.com/assets/1212178/15876411/29e65ba4-2cc2-11e6-87a0-5f415037a670.png)
https://bluegreenway.cartodb.com/viz/44738a5e-2ceb-11e6-abb5-0ea31932ec1d/public_map

So they idea is that the open spaces and the projects will function exactly the same, but we'll use this field to style them differently.

**Comment by ericsoco** [comment]
@almccon @emily is this flag coming through anywhere i can see it on the frontend? I need it for the zone page (the image you attached at the top of this issue). Are these the projects in http://dev.sfparksalliance.org/feeds/locations.json/1 that have `"Location Category": "Park or Playground",`, and the non-open-space projects are those with `"Location Category": "Other",`?

**Comment by ericsoco** [comment]
(btw, who makes keys with spaces in them? weird.)

**Comment by almccon** [comment]
I'm not convinced they've populated the `Location Category` completely or necessarily correctly.
You can pull from the GeoJSON if you like, instead of the API. I have the `category` field in the GeoJSON.

**Comment by Emily** [comment]
@ericsoco wrong Emily :)

**Comment by ericsoco** [comment]
oops. /cc @emilyhobson ^^.

**Comment by almccon** [comment]
Now styled in Leaflet: 

![screen shot 2016-06-24 at 24 jun 7 07 41](https://cloud.githubusercontent.com/assets/1212178/16354150/6f80f932-3a3f-11e6-9096-24c3c479c777.png)
