### ISSUE TITLE
Add Open Spaces to Zone pages

### ISSUE THREAD

**Issue by clhenrick** [stamen/bluegreenway#65]
Ideally these will be coming from a BGW specific / filtered version of the open spaces geojson file. Relates to #61

**Comment by emilyhobson** [comment]
This will come from the BGW specific / filtered version of the locations geojson file, category = parks, zone = foo.

**Comment by clhenrick** [comment]
Open spaces content will be integrated from the locations / projects JSON feed on ZONE pages while it's up to us to work with BGW to reconcile the projects GEOJSON / polygon data file. Reposting from our convo in Slack @emilyhobson @almccon
