### ISSUE TITLE
Join CMS Feed data to Projects Polygons in Map View

### ISSUE THREAD

**Issue by clhenrick** [stamen/bluegreenway#67]
For Stories, Events, & Projects; unless BGW or Justin tell us other wise. Requires a source of truth for Project Polygons' unique ids that will be in each 3 CMS feeds.

**Comment by emilyhobson** [comment]
YES

**Comment by ericsoco** [comment]
The joining is done on the FE code side, and the specific implementations (i.e. #85, #126) are accounted for elsewhere. So, closing this.
