### ISSUE TITLE
Reconcile project polygon IDs with location IDs from API

### ISSUE THREAD

**Issue by almccon** [stamen/bluegreenway#69]
The locations feed (http://dev.sfparksalliance.org/feeds/locations.json) has an ID field for each project which comes from Drupal and which should be the primary key for joining events and news stories with their geometries.

Currently the geometry file [bgw_projects.geojson](https://github.com/stamen/bluegreenway/blob/master/geodata/bgw_projects.geojson) has some IDs that correspond with the locations feed, but most of the IDs are fake.

We need to update the IDs in `bgw_projects.geojson` to match the corresponding locations in the locations feed. If projects are missing in the locations feed, we need to add those projects to Drupal and obtain a new ID at the time of database insert.

**Comment by almccon** [comment]
This will make #67 work, although some polygons should join correctly right now (just not all of them)

**Comment by ericsoco** [comment]
Related: #78.
@almccon please do the same thing here -- let us know where we're at so we can bug the client as necessary.

**Comment by ericsoco** [comment]
And so I know what to expect as I seam things together on the FE.

**Comment by ericsoco** [comment]
I am starting to see some new location ids trickling in. E.g. I'm seeing these ids associated with Stories (there may be more in the future, i dunno):

```
6377
6378
6379
6380
```

Maybe now's a good time to check in on the locations in the CMS, see what's new?

**Comment by ericsoco** [comment]
Right now I'm seeing this from the CMS:

```
projects: ["[6375] Islais Creek: { zoneId: Pier 70/Central Waterfront }", "[6376] India Basin Shoreline Park: { zoneId: India Basin }", "[6377] Pier 70/Central Waterfront: { zoneId: Pier 70/Central Waterfront }", "[6378] Mission Bay/Mission Rock: { zoneId: Mission Bay/Mission Rock }", "[6379] India Basin: { zoneId: India Basin }", "[6380] Hunters Point Naval Shipyard/Candlestick: {…oneId: Hunters Point Naval Shipyard/Candlestick }", "[6381] China Basin Park: { zoneId: Mission Bay/Mission Rock }", "[6382] Yosemite Slough: { zoneId: Hunters Point Naval Shipyard/Candlestick }", "[6383] Pier 70: { zoneId: Pier 70/Central Waterfront }", "[6384] Mission Rock: { zoneId: Mission Bay/Mission Rock }", "[6385] Mission Bay Parks: { zoneId: Mission Bay/Mission Rock }", "[6386] Mission Creek Park: { zoneId: Mission Bay/Mission Rock }", "[6387] Mission Bay Commons Park: { zoneId: Mission Bay/Mission Rock }", "[6388] Chase Center/Bayfront Park : { zoneId: Mission Bay/Mission Rock }", "[6389] Former Potrero Power Plant: { zoneId: Pier 70/Central Waterfront }", "[6390] Warm Water Cove: { zoneId: Pier 70/Central Waterfront }", "[6391] Heron’s Head Park: { zoneId: India Basin }", "[6392] PG&E Hunters Point Power Plant: { zoneId: India Basin }", "[6393] 900 Innes: { zoneId: India Basin }", "[6394] Hunters Point Shipyard: { zoneId: Hunters Point Naval Shipyard/Candlestick }", "[6395] Candlestick Point State Recreation Area: { zoneId: Hunters Point Naval Shipyard/Candlestick }", "[6396] 700 Innes: { zoneId: India Basin }"]
```

And this in our projects geojson:

```
projects geojson: ["[null] null", "[null] null", "[14] Pier 64 Shoreline Access", "[21] Mission Creek Shoreline South", "[23] Pier 52 Boat Launch", "[27] India Basin Open Space", "[188] Pier 94 Wetlands", "[304] Bayfront Park", "[383] Agua Vista Park and Fishing Pier", "[501] Cargo Way", "[506] Illinois Street", "[507] 24th Street", "[508] Terry Francois Blvd Improvements", "[510] Hudson Avenue Right-Of-Way Improvements", "[5100] Jennings St/Hunters Point Blvd/Innes Ave", "[6375] Islais Creek North-West", "[6376] India Basin Shoreline Park", "[6381] China Basin Park", "[6382] Yosemite Slough Wetland", "[6385] Mission Bay Parks 23 & 24", "[6386] Mission Creek Shoreline North", "[6389] Power Plant Shoreline Access", "[6390] Warm Water Cove Park", "[6391] Heron's Head Park", "[6392] PG&E Shoreline", "[6393] 900 Innes", "[6394] Hunters Point Shipyard Open Spaces North", "[6395] Candlestick Point State Recreation Area", "[6396] 700 Innes", "[99999] Chase Center Arena (Warriors)", "[699968] Pier 70 Upland Open Spaces", "[987987] Hunters Point Shipyard Open Spaces South", "[998887] Third and Cargo Gateway", "[999000] Pier 70 Slipways Park", "[999999] Tulare Park/Islais Creek North-East", "[999999] Islais Landing/Islais Creek South", "[9999888] Pier 70 Crane Cove Park"]
```

Looks like there are still some locations that are on your list that are not yet entered into the CMS. Let's get a handle on that ASAP so the client can get that done.

**Comment by almccon** [comment]
Everything in the API now has matching IDs in the GeoJSON. There are still several features in the GeoJSON that do not exist in the API, but with #157 nothing will break in those cases. Client says they don't intend to add those remaining features to the API for now. When they _do_ add new stuff to the API, we can revisit.
