### ISSUE TITLE
Geo Spatial Data sources for map layers

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#7]
Assessment of data resources, including detailed list of city GIS, calendar feeds, Stamen code/tools to deploy

Where is the Data?
- Live feed from sfparksalliance.org 
- \- Events
- \- Parks
## \- - Projects
- Spatial data from static files hosted on CartoDB.com 
- Port of San Francisco

Targeted use of other public data sets (based on story needs)
HIGH INTEREST:
●Waterfront recreation
●playgrounds/community gardens
●green connections project (planning)
●open space (planning)
●tree cover
●census data
●density
●development pipeline layer
●transportation - streets, muni, bike (MTA)

CURIOUS ABOUT
●impervious surface layer
●sea level rise
●health indicators by zip code
●health access layer
●EPA/brownfields/toxics
●sewer flooding (land side from 311 calls)v

**Comment by almccon** [comment]
📄📄📄

**Comment by almccon** [comment]
Green connections network https://data.sfgov.org/Energy-and-Environment/Green-Connections-Network/3n7h-3jam on CartoDB: https://stamen.cartodb.com/u/stamen-org/tables/green_connections_network_final

Open spaces (planning) https://data.sfgov.org/Culture-and-Recreation/Open-Spaces-City-Planning/zsre-apvm on CartoDB: https://stamen.cartodb.com/u/stamen-org/tables/planning_openspaces

Urban tree canopy (blobs) https://data.sfgov.org/Energy-and-Environment/San-Francisco-Urban-Tree-Canopy/w9tk-3w8c on CartoDB: https://stamen.cartodb.com/u/stamen-org/tables/sf_urban_tree_canopy

Street trees https://data.sfgov.org/City-Infrastructure/Street-Tree-List/tkzw-k3nq on CartoDB: https://stamen.cartodb.com/u/stamen-org/tables/street_tree_list

Development pipeline, here's 2015Q4 which is the latest I could find: https://data.sfgov.org/Housing-and-Buildings/San-Francisco-Development-Pipeline-2015-Quarter-4/ra2x-jzmk

**Comment by ericsoco** [comment]
@almccon in case it wasn't clear, the SFPA data are coming from their CMS via our canopy-dwelling birdfriend in Mexico. :palm_tree::bird::neckbeard:

**Comment by almccon** [comment]
Growing list here: https://docs.google.com/document/d/1qX-rIuCkLBMFsr_EduSY1ysmdsXHR8quVAiP8r3tkgI/

**Comment by emilyhobson** [comment]
@almccon Focus on P1 sources

**Comment by emilyhobson** [comment]
Combine benches and tables
No development pipeline

**Comment by almccon** [comment]
These will be separate CartoDB tile layers that the front end can toggle on or off. I will style them.

**Comment by emilyhobson** [comment]
Have the data feeds been pulled into Carto, @almccon ?

**Comment by almccon** [comment]
Um. What data feeds?

**Comment by clhenrick** [comment]
@almccon do you know which dataset corresponds to the following layers in the UI? Do we have them all from BGW? 

![screen shot 2016-05-24 at 10 02 52 am](https://cloud.githubusercontent.com/assets/161748/15506737/b91b9bcc-2196-11e6-8e64-607d5aaacbb6.png)

**Comment by almccon** [comment]
We totally don't have them all, and Alec said we shouldn't take that list as gospel. 

I will produce as many of those as I can as separate viz.json layers. But we won't have all of them.

**Comment by clhenrick** [comment]
@almccon they don't need to be separate vis.json layers, in fact it's better if they are not. If you could let me know what the layer names <-> geodata mapping I can pull them directly as a tile layer or geojson overlay.

**Comment by almccon** [comment]
Also, currently I have the bikes and green connectors in the basemap layer. I can pull those out into their own layers... But it might be nicer to leave them in there, and have fewer layer toggles. For now I'll separate them, just so you have some toggle layers to test with.

**Comment by almccon** [comment]
Here's one, for example: https://bluegreenway.cartodb.com/tables/bicycle_network/map I move the CartoCSS styling out of the main basemap viz and applied it just to this layer. Is this what you have in mind? Note, I still need to make the background transparent.

As for pulling these as GeoJSON overlays, we don't need any interactivity with these (I had assumed) and we also don't want them to be too distracting... I think we'll need the subtlety of CartoCSS styling.

**Comment by almccon** [comment]
And this is the green connections: https://bluegreenway.cartodb.com/tables/green_connections_network_final/map

**Comment by clhenrick** [comment]
The way I have done layer toggling with CartoDB in the past is either through iterating through a vis.json's sublayers and hiding / showing them OR creating a new sublayer. The latter requires having to pass CartoCSS & SQL which we probably want to avoid. 

I think there's a way you can create a map with multiple `vis.json`'s, but I'm not sure if it's the right approach or not for this many layers that are to be toggleable. But it may be worth investigating given that the BGW CDB account (assuming it's a free plan?) will have a limit on the number of layers you can add to a visualization.

**Comment by almccon** [comment]
And @clhenrick I'm not trying to be evasive not giving you the rest of the layer names <-> geodata mapping. It's just that I don't have them ready and pushed to CartoDB yet.

**Comment by almccon** [comment]
Added benches and picnic tables: https://bluegreenway.cartodb.com/tables/benches_and_picnic_tables/map
also here: https://github.com/stamen/bluegreenway/blob/master/geodata/SFRPD-benches-and-picnic-tables.geojson

![screen shot 2016-05-24 at 24 may 4 36 37](https://cloud.githubusercontent.com/assets/1212178/15523238/ecf3593a-21cd-11e6-8522-49e654b48a74.png)

**Comment by almccon** [comment]
See #11 for boat launches

**Comment by emilyhobson** [comment]
We have the stuff we need for the layer per #66, correct? If so, let's close this one.
