### ISSUE TITLE
Change React Router history from browser history to hash history 

### ISSUE THREAD

**Issue by clhenrick** [stamen/bluegreenway#71]
@mojodna brought this up in a discussion yesterday in which we determined to avoid server side rendering (#23) for initial launch / phase 1.

I'm curious though if we still can use **browser history** even if we aren't using server side rendering? Is switching to hash history a good idea because we want to avoid any server configuration and just hand it off as a static site?

**Comment by clhenrick** [comment]
For reference: https://github.com/reactjs/react-router/blob/master/docs/guides/Histories.md#should-i-use-hashhistory

**Comment by sethfitz** [comment]
We can't use browser history because links that have been browsed to won't be share-able.

If we're embedded in a single page, e.g. `/`, and navigate to `/projects` (managed by React Router), Drupal will 404 if you copy the link and send it to someone else whereas `/#/projects` will load `/` from Drupal and React Router will look up `/projects`.

**Comment by clhenrick** [comment]
@mojodna I didn't realize we are hosting this on Drupal.

**Comment by sethfitz** [comment]
Maybe we're not, but I'm pretty sure BGW is responsible for hosting.

We'd need either server-side rendering or wildcard path matching (lightweight server-side rendering) for browser history to work in any case.

**Comment by clhenrick** [comment]
Noting that we are currently using `react-router-redux` library for integrating React Router & Redux, however from the [docs](https://github.com/reactjs/react-router-redux) of that library it states:

> This library is not necessary for using Redux together with React Router. You can use the two together just fine without any additional libraries. It is useful if you care about recording, persisting, and replaying user actions, using time travel. **If you don't care about these features, just use Redux and React Router directly.**

**Comment by clhenrick** [comment]
also: https://github.com/reactjs/redux/issues/637

So basically it seems like unless we need features like time travel with Redux we don't need `react-router-redux`. 

Will ping @ericsoco & @sconnelley for their thoughts.

**Comment by sconnelley** [comment]
Browser history should not be the default for projects and definitely not use it when we don't have access to configure the server-side.
As far as `react-router-redux`, I don't remember ever using it before but I am using it on Lake Tahoe.  And so far I don't really see any reason to use it but at the same time it isn't really creating any difficulties either.  Maybe @ericsoco has more info.

**Comment by sconnelley** [comment]
BTW I had to use this little rewrite to get Lake Tahoe to successfully route.

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    RewriteRule ^index\.html$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /lake-tahoe/show/latest/index.html [L]
 </IfModule>
```

**Comment by clhenrick** [comment]
@sconnelley thanks, so are you using `hashHistory` for Lake Tahoe? Or is that a server side rendered app?

**Comment by sconnelley** [comment]
Currently, it's using browser history and it's not a server-side rendered app.  I am using that rewrite snippet above to rewrite the urls. I don't want to change it to hash history till Eric gets back since he set it up.
