### ISSUE TITLE
Add Place Holder Images

### ISSUE THREAD

**Issue by clhenrick** [stamen/bluegreenway#73]
So far for:
- [ ] events with no photos
- [x] zone pages (header image ~~& item-description image~~)

**Comment by emilyhobson** [comment]
To @alecburch to sort out images

**Comment by clhenrick** [comment]
@emilyhobson believe @alecburch has given me placeholder images for calendar events & one for the zone landing pages. As far as I know we don't need them anywhere else on the site. Re-assigning myself.

**Comment by emilyhobson** [comment]
Can this be closed, @clhenrick ?

**Comment by ericsoco** [comment]
Done: https://github.com/stamen/bluegreenway/blob/master/src/components/Event.js#L7-L11
