### ISSUE TITLE
Upgrade React Router programatic navigation method

### ISSUE THREAD

**Issue by clhenrick** [stamen/bluegreenway#74]
Right now when toggling Map / Page View the following warning is displayed in the console as a result of doing `this.props.history.push('path/to/page');`

> browser.js:49 Warning: [react-router] `props.history` and `context.history` are deprecated. Please use `context.router`. http://tiny.cc/router-contextchanges

Shouldn't be a big deal to change but will require looking into (_note to self_).

@sconnelley have you run into this with Tahoe at all? Currently I'm experiencing it when doing:
`this.props.history.push('path/to/page');`

**Comment by sconnelley** [comment]
Seems to be a react-router [issue](https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.0.0.md#changes-to-thiscontext) that is solved in version >= 2.4.0

But I haven't really looked into too much...

**Comment by sconnelley** [comment]
I update `react-router` to v2.4.1 and added the [`withRouter` HoC](https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.4.0.md).  Also, replaced any instance of `this.props.history.push` to `this.props.router.push` and seems to have removed the warnings.

**Comment by clhenrick** [comment]
thanks @sconnelley, you're using this method in Tahoe correct?

**Comment by sconnelley** [comment]
@clhenrick - yes, https://github.com/stamen/lake-tahoe/commit/2246e8d460a527198e72ad9b55e98e5518ba9801

**Comment by ericsoco** [comment]
Closed via https://github.com/stamen/bluegreenway/commit/59ba80e85b1867fc84bf8fdabc0e5571d476e476.
