### ISSUE TITLE
Make sure links in Nav Bar stay highlighted on nested routes

### ISSUE THREAD

**Issue by clhenrick** [stamen/bluegreenway#75]
Un-nesting the Routes to fix issues I was running into using `:mode` disabled the `.active` class on the currently selected nav item in the nav bar. Figure out how to re-enable them.

**Comment by ericsoco** [comment]
@clhenrick you mean like http://studio.stamen.com/bluegreenway/show/latest/#/projects/page/mission_bay_mission_rock? looks like it's working to me, can we close this?

**Comment by clhenrick** [comment]
yeah, looks like it's fixed
