### ISSUE TITLE
Zone content - hardcoded

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#76]
Zone content will be hardcoded and provided by the client. I can update with text edits in Github once we place the initial content from the client.

**Comment by clhenrick** [comment]
Need content to implement

**Comment by emilyhobson** [comment]
Can you see the zone descriptions in the locations feed, @ericsoco ?

**Comment by ericsoco** [comment]
No. All I have in the locations feed in terms of zones is e.g.:
`"BGW Zone": "India Basin",`
I'm using that as an id, to sync the CMS data with the geojson.

There are two fields that I need (hardcoded is fine) --
`description`: the text that will appear on an [individual zone page](https://marvelapp.com/141icj3#10762760);
`image`: the image that will appear on an [individual zone page](https://marvelapp.com/141icj3#10762760).

Those should be hardcoded into the geojson `properties` for each zone. Once we have images and text, this should be assigned to @almccon. My code will (hopefully) automatically pick up and render those fields once they're populated.

**Comment by emilyhobson** [comment]
Pinged Angelica again (they should have these ready and approved).

**Comment by emilyhobson** [comment]
Text here, photos TK
https://drive.google.com/open?id=0B5tBIGe_xercSGNxcTlteXdJR2s

**Comment by almccon** [comment]
Descriptions are in the `description` field, and image file names are in `image`, all of which are in the `static/img/` folder.

**Comment by emilyhobson** [comment]
Are you still blocked on this, @almccon ?

**Comment by ericsoco** [comment]
This is done now, zones and their content are appearing correctly on the site.
