### ISSUE TITLE
Style zone overlays on Projects page

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#81]

**Comment by almccon** [comment]
I assume this means:
- [x] Style the GeoJSON overlays for the projects (using two colors, one for "open spaces" and one for regular "projects" per #61). See also #68 where we talked about coloring the projects based on what zone they're in (which I assume we're not doing)
- [x] Style the CartoDB toggleable context layers (see #66 and #59 and #7)

**Comment by ericsoco** [comment]
@almccon I just updated the issue title to reflect the remaining open task.

**Comment by almccon** [comment]
GeoJSON projects / open spaces now styled in Leaflet: 

![screen shot 2016-06-24 at 24 jun 7 07 41](https://cloud.githubusercontent.com/assets/1212178/16354150/6f80f932-3a3f-11e6-9096-24c3c479c777.png)
