### ISSUE TITLE
Location / Project photos

### ISSUE THREAD

**Issue by emilyhobson** [stamen/bluegreenway#89]
Don't appear to be coming through the CMS feed

**Comment by emilyhobson** [comment]
Has this been resolved in the feed, @ericsoco ?

**Comment by ericsoco** [comment]
Not sure. Justin said he would add to production (I told him adding to dev not necessary), but it appears that BGW hasn't added projects to production CMS yet.

**Comment by emilyhobson** [comment]
#76

**Comment by ericsoco** [comment]
Only thing left here is #129.
