### ISSUE TITLE
Legend for toggleable POIs

### ISSUE THREAD

**Issue by almccon** [stamen/bluegreenway#91]
In #66 we grouped the boat launches (existing and planned) together with picnic tables and benches. You can toggle them all on/off as a group, not individually.

So now we need a legend for those four data points. Not sure where it should go, or what it should look like.

The default legend in the CartoDB viewer is approximate: 

![screen shot 2016-06-09 at 9 jun 9 47 27](https://cloud.githubusercontent.com/assets/1212178/15954424/b876ddba-2e8b-11e6-8de1-cc5606f19258.png)

The exact symbology I'm using right now (subject to change based on client feedback) is (in simplified CartoCSS):
# combined_poi_tables[type="Bench"] {

  marker-fill: #725555;
  marker-line-color: #FFF;
}
# combined_poi_tables[type="Picnic Table"] {

  marker-fill: #12700c;
  marker-line-color: #FFF;
}
# combined_poi_tables[type="Boat Existing"] {

  marker-fill: #5CA2D1;
  marker-line-color: #1f78b4;
}
# combined_poi_tables[type="Boat Planned"] {

  marker-fill: #666;
  marker-line-color: darken(#1F78B4,20);
}

Also, the boat launches appear slightly larger than the benches and picnic tables because of their darker stroke.

**Comment by ericsoco** [comment]
Assigning to @alecburch for legend + icon design goodness.

**Comment by almccon** [comment]
Here are @alecburch's colors from #134, now implemented on the map:

Benches: #8bc954
Tables: #279ab7
Boats, existing: #043d58
Boats, planned: #ffff98

The legend in this screenshot is visible in CartoDB, but not on the site itself. Still need an actual legend. Really, the benches and tables are self-explanatory (so legends for them are optional), but we need a way to indicate which boat launches are existing and which are planned.

![screen shot 2016-07-05 at 5 jul 1 03 20](https://cloud.githubusercontent.com/assets/1212178/16598199/9ba54a3e-42b1-11e6-8325-140f268d1125.png)

**Comment by alecburch** [comment]
Design for legend:

![screen shot 2016-07-07 at 3 19 22 pm](https://cloud.githubusercontent.com/assets/5263476/16671777/42ae67f2-4456-11e6-8ae7-8a169709b14b.png)
