### ISSUE TITLE
New homepage layout that accommodates 2 featured persons instead of 3

### ISSUE THREAD

**Issue by clhenrick** [stamen/bluegreenway#94]
Current layout uses 3 featured person stories, but we will only have 2 for launch. We need to adjust the layout to accommodate this.

cc @alecburch

**Comment by alecburch** [comment]
let's use this layout. 

![screen_shot_2016-06-14_at_12 45 14_pm_1024](https://cloud.githubusercontent.com/assets/5263476/16062286/00418e9c-3247-11e6-97f9-f49c3236a232.png)

**Comment by emilyhobson** [comment]
done
