### ISSUE TITLE
add drop shadows

### ISSUE THREAD

**Issue by alecburch** [stamen/bluegreenway#98]
- [x] nav bar
- [x] footer
- [x] map/page toggle
- [x] header image
- [x] calendar/filters
- [x] events/stories tiles
- [x] zone mini maps
- [x] twitter feed

**Comment by ericsoco** [comment]
Note that I already have a [SASS variable](https://github.com/stamen/bluegreenway/blob/master/scss/_variables.scss#L17) for the site's `box-shadow`.

**Comment by alecburch** [comment]
lets tone them back a bit. 

`box-shadow: 0 0 5px 4px rgba(0,0,0,.1)`

**Comment by ebrelsford** [comment]
Fixed in d4fcd88a.

**Comment by alecburch** [comment]
Alec is stewpid. Remove drop shadow from all elements that aren't white (story & event tiles). @ericsoco

**Comment by ebrelsford** [comment]
Removed shadow from event and story tiles, @alecburch, but wondering if you also want it removed from the header images since they're not white?

**Comment by ericsoco** [comment]
@ebrelsford on @alecburch's behalf I can say yes please.

**Comment by alecburch** [comment]
yes, thank you. sorry for the back and forth.
